### ISSUE TITLE
incorrect reflection in 11.0.0

### ISSUE THREAD

**Issue by andriuha1987** [sbtqa/page-factory-2#199]
Обнаружено как мне кажется некорректное поведение в ru.sbtqa.tag.pagefactory.reflection.DefaultReflection (потому что в pf1 отрабатывает)

@Override
public void executeMethodByTitle(Object context, String title, Object... param) throws NoSuchMethodException {
                
              
Имеем шаг в фиче
* пользователь (авторизуется в системе Back Office)
                
В Page имеем 2 метода, которые принимают на вход разное кол-во аргументов
                
@ActionTitle("авторизуется в системе Back Office")
    public void authorizedInSystem() {
        authorized(Props.get("antifrodUsername"), Props.get("antifrodPassword"));
    }
@ActionTitle("авторизуется в системе Back Office")
    public void authorizedInSystem(String userName, String userPassword) {
        authorized(userName, userPassword);
    }
  
Получаем через раз ошибку (потому что видимо список методов считывается в разном порядке)
                
                java.lang.IllegalArgumentException: wrong number of arguments
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at ru.sbtqa.tag.pagefactory.reflection.DefaultReflection.executeMethodByTitle(DefaultReflection.java:58)
                at ru.sbtqa.tag.pagefactory.junit.CoreSteps.action_aroundBody2(CoreSteps.java:77)
                at ru.sbtqa.tag.pagefactory.junit.CoreSteps$AjcClosure3.run(CoreSteps.java:1)
                at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                at ru.sbtqa.tag.pagefactory.allure.JunitReporter.handleStep(JunitReporter.java:25)
                at ru.sbtqa.tag.pagefactory.aspects.JUnitCoreStepAspect.handleStep(JUnitCoreStepAspect.java:13)
                at ru.sbtqa.tag.pagefactory.junit.CoreSteps.action(CoreSteps.java:76)
                at ru.sbtqa.tag.stepdefs.ru.CoreStepDefs.action(CoreStepDefs.java:44)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at cucumber.runtime.Utils$1.call(Utils.java:32)
                at cucumber.runtime.Timeout.timeout(Timeout.java:16)
                at cucumber.runtime.Utils.invoke(Utils.java:26)
                at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)

**Comment by andriuha1987** [comment]
Подскажите, планируется ли исправление?

**Comment by kosteman** [comment]
Да, на этой неделе возьмем в работу

**Comment by kosteman** [comment]
исправлено в [11.1.1](https://github.com/sbtqa/page-factory-2/releases/tag/11.1.1)
