### ISSUE TITLE
Feature is not parsed with \|

### ISSUE THREAD

**Issue by andriuha1987** [sbtqa/page-factory-2#231]
Для версии 11.2.0
Пример. в фиче есть такой кусок (должен быть экранирующий слеш  \\|)

* отправить через SOAP "перевод частному лицу"
  | данные1   | Autotest 22245 Test |
  | данные2   | \\|pdf\\|pdf                  |
  | данные3   | -172820                    |
 
Получаем ошибку при сборке
cucumber.runtime.CucumberException: gherkin.ParserException$CompositeParserException: Parser errors:
(16:7): inconsistent cell count within the table
(20:7): inconsistent cell count within the table
(24:7): inconsistent cell count within the table
(28:7): inconsistent cell count within the table
                at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:60)
                at ru.sbtqa.tag.pagefactory.utils.GherkinSerializer.lambda$0(GherkinSerializer.java:62)
                at java.util.ArrayList.forEach(ArrayList.java:1249)
                at ru.sbtqa.tag.pagefactory.utils.GherkinSerializer.reserializeFeatures(GherkinSerializer.java:43)
                at ru.sbtqa.tag.pagefactory.aspects.FragmentsAspect.replaceSteps(FragmentsAspect.java:45)
                at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:311)
                at cucumber.api.junit.Cucumber.<init>(Cucumber.java:81)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
                at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
                at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
                at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
                at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
                at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
                at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
                at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
                at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
                at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: gherkin.ParserException$CompositeParserException: Parser errors:
(16:7): inconsistent cell count within the table
(20:7): inconsistent cell count within the table
(24:7): inconsistent cell count within the table
(28:7): inconsistent cell count within the table
                at gherkin.Parser.parse(Parser.java:143)
                at gherkin.Parser.parse(Parser.java:118)
                at gherkin.Parser.parse(Parser.java:114)
                at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:56)
                ... 20 more

**Comment by clicman** [comment]
Так это невалидная фича. 

Отправлено с iPhone

**Comment by andriuha1987** [comment]
Валидная. с page factory 1 все нормально. Это экранирование же символа |

**Comment by andriuha1987** [comment]
Вот пример описания
https://stackoverflow.com/questions/12960803/can-i-escape-the-pipe-in-specflow-or-gherkin

**Comment by clicman** [comment]
Ахахаха. Почта айфона заэкранировала экранирующие символы и я их не увидел 😂

**Comment by clicman** [comment]
Тогда это баг.

**Comment by Sergo101010100** [comment]
а когда релиз с этим исправлением планируется?

**Comment by clicman** [comment]
Release 12.0.0
