### ISSUE TITLE
Aspects in 12.0.0

### ISSUE THREAD

**Issue by andriuha1987** [sbtqa/page-factory-2#239]
Нужна консультация по версии 12.0.0

Подскажите, были ли какие-то изменения с аспектами при переходе от 11.2.0 к 12.0.0

В нашем проекте имеются свои аспекты, пример кода который работал корректно с версией 11.2.0
@Around(value = "execution(@cucumber.api.java.ru.* * *(..))")
public Object ignoreDBSteps(ProceedingJoinPoint joinPoint) throws Throwable {
    //какой-то код
    return joinPoint.proceed();
}

С 12.0.0 для некоторых методов стала выдаваться ошибка (для метода с такими параметрами 
public void createUniversallyRuleSmartVista(String ruleName, String lastName, String firstName, String patronymicName, String policy, String event) )

java.lang.ClassCastException: java.lang.String cannot be cast to org.aspectj.lang.JoinPoint
                at ru.sbt.antifrod.fl.steps.common.CommonRules$AjcClosure55.run(CommonRules.java:1)
                at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                at ru.sbt.antifrod.fl.utils.aspects.StepDefsAspects.ignoreDBSteps(StepDefsAspects.java:54)

**Comment by clicman** [comment]
Нужен дебаг.

**Comment by SandraBarmina** [comment]
Аспекты не правились и новых не заводилось. Надо хотя бы код, что там в строке 54?

**Comment by andriuha1987** [comment]
> Аспекты не правились и новых не заводилось. Надо хотя бы код, что там в строке 54?

return joinPoint.proceed();

**Comment by SandraBarmina** [comment]
Я ничем не смогу помочь, если мне не дать больше информации

Аспект выглядит довольно странно. во-первых, аннотация с маленькой буквы, во-вторых, он не конкретизирован под определенный метод и вызывается каждый раз при обращении к чему-либо из  cucumber.api.java.ru. в-третьих, почему именно аспект? в-четвертых, что там происходит в методе?

Можете где-нибудь показать?

**Comment by andriuha1987** [comment]
> Я ничем не смогу помочь, если мне не дать больше информации
> 
> Аспект выглядит довольно странно. во-первых, аннотация с маленькой буквы, во-вторых, он не конкретизирован под определенный метод и вызывается каждый раз при обращении к чему-либо из cucumber.api.java.ru. в-третьих, почему именно аспект? в-четвертых, что там происходит в методе?
> 
> Можете где-нибудь показать?

То, что с маленькой буквы это просто видимо сам github так порой форматирует, да он неконкретизирован, в методе просто проверки, который сводятся к тому, выполнить ли степ или нет. по сути два пути - один return null, другое return joinPoint.proceed();

Постараюсь собрать побольше информации при дебаге, просто ставлю версию 11.2.0 всё корректно выполняется, ставлю 12.0.0 падает с ошибкой. и пока не смог разобраться что же изменилось в коде, что такая разница.

**Comment by SandraBarmina** [comment]
> > Я ничем не смогу помочь, если мне не дать больше информации
> > Аспект выглядит довольно странно. во-первых, аннотация с маленькой буквы, во-вторых, он не конкретизирован под определенный метод и вызывается каждый раз при обращении к чему-либо из cucumber.api.java.ru. в-третьих, почему именно аспект? в-четвертых, что там происходит в методе?
> > Можете где-нибудь показать?
> 
> То, что с маленькой буквы это просто видимо сам github так порой форматирует, да он неконкретизирован, в методе просто проверки, который сводятся к тому, выполнить ли степ или нет. по сути два пути - один return null, другое return joinPoint.proceed();
> 
> Постараюсь собрать побольше информации при дебаге, просто ставлю версию 11.2.0 всё корректно выполняется, ставлю 12.0.0 падает с ошибкой. и пока не смог разобраться что же изменилось в коде, что такая разница.

А в стек трейсе что-то еще есть? вероятно он просто дальше проваливается еще куда-то. Менялась логика работы с шагами, но не в аспектах. Но proceed() может просто перехватывает то, что менялось

**Comment by andriuha1987** [comment]
> > > Я ничем не смогу помочь, если мне не дать больше информации
> > > Аспект выглядит довольно странно. во-первых, аннотация с маленькой буквы, во-вторых, он не конкретизирован под определенный метод и вызывается каждый раз при обращении к чему-либо из cucumber.api.java.ru. в-третьих, почему именно аспект? в-четвертых, что там происходит в методе?
> > > Можете где-нибудь показать?
> > 
> > 
> > То, что с маленькой буквы это просто видимо сам github так порой форматирует, да он неконкретизирован, в методе просто проверки, который сводятся к тому, выполнить ли степ или нет. по сути два пути - один return null, другое return joinPoint.proceed();
> > Постараюсь собрать побольше информации при дебаге, просто ставлю версию 11.2.0 всё корректно выполняется, ставлю 12.0.0 падает с ошибкой. и пока не смог разобраться что же изменилось в коде, что такая разница.
> 
> А в стек трейсе что-то еще есть? вероятно он просто дальше проваливается еще куда-то. Менялась логика работы с шагами, но не в аспектах. Но proceed() может просто перехватывает то, что менялось

Сложно понять, что происходит. Но для другой функции возникла такая ошибка

java.lang.NoSuchMethodError: ru.sbt.antifrod.fl.pages.scheduleraaa.ProcedureSchedulerAAA.checkTaskLogEnd_aroundBody18(Lru/sbt/antifrod/fl/pages/scheduleraaa/ProcedureSchedulerAAA;Ljava/lang/String;Lorg/aspectj/lang/JoinPoint;)V

                at ru.sbt.antifrod.fl.pages.scheduleraaa.ProcedureSchedulerAAA$AjcClosure19.run(ProcedureSchedulerAAA.java:1)
                at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                at ru.sbt.antifrod.fl.utils.aspects.StepDefsAspects.ignoreDBSteps(StepDefsAspects.java:54)
                at ru.sbt.antifrod.fl.pages.scheduleraaa.ProcedureSchedulerAAA.taskRunSuccessfully(ProcedureSchedulerAAA.java:70)

При этом у нас имеются две реализации (идет запуск с одним параметром). если закомментировать реализацию с двумя параметрами, то всё ок. По ошибке которую описывал выше, в stacktrace больше нет ничего. Пытался проваливаться глубже, получал такое как на скрине
![аспекты](https://user-images.githubusercontent.com/48748886/57299937-7507b200-70de-11e9-87e8-526464cd2af0.png)

@Тогда("задача \"([^\"]+)\" успешно запущена")
public void taskRunSuccessfully(String name) {
    appearsMessage("Задача \"" + name + "\" успешно запущена");
}

@Тогда("не удалось запустить задачу \"([^\"]+)\" запущена блокирующая задача \"([^\"]+)\"")
public void taskRunSuccessfully(String name, String blockName) {
    appearsMessage("Не удалось запустить задачу \"" + name + "\" : Уже запущена блокирующая задача \"" + blockName + "\"");
}

**Comment by Sergo101010100** [comment]
@SandraBarmina,  в итоге есть какие то идеи? Потому что ситуация похожа на прошлый баг https://github.com/sbtqa/page-factory-2/issues/199

**Comment by clicman** [comment]
try 12.0.3 version

**Comment by Sergo101010100** [comment]
в 12.0.3 работает...
