### ISSUE TITLE
NPE parseTestDataProvider 12.0.3

### ISSUE THREAD

**Issue by Sergo101010100** [sbtqa/page-factory-2#248]
pf 12.0.3
properties provider 5.0.0
Негативный вариант
feature
`* он (выбирает) "Список сотрудников" "${users.antifrodUsername}"`

настройки application.properties
`data.type = properties
data.folder = src/test/resources/config/ift
data.initial.collection = common
`
Получаем ошибку
`java.lang.NullPointerException
at ru.sbtqa.tag.datajack.providers.AbstractDataProvider.parseTestDataProvider(AbstractDataProvider.java:394)
at ru.sbtqa.tag.datajack.providers.AbstractDataProvider.getByPath(AbstractDataProvider.java:100)
at ru.sbtqa.tag.pagefactory.data.DataUtils.parseDataTagValue(DataUtils.java:66)
at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceDataPlaceholders(DataReplacer.java:136)
at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceData(DataReplacer.java:111)
at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceStepArguments(DataReplacer.java:87)
at ru.sbtqa.tag.pagefactory.data.DataReplacer.replace(DataReplacer.java:42)
at ru.sbtqa.tag.pagefactory.data.DataReplacer.replace(DataReplacer.java:34)
at ru.sbtqa.tag.pagefactory.aspects.DataAspect.sendStepStart(DataAspect.java:119)
at cucumber.runner.EventBus.send_aroundBody4(EventBus.java:25)
at cucumber.runner.EventBus.send_aroundBody6(EventBus.java:25)
at cucumber.runner.EventBus.send_aroundBody8(EventBus.java:25)
at cucumber.runner.EventBus.send_aroundBody10(EventBus.java:25)
at cucumber.runner.EventBus.send(EventBus.java:25)
at cucumber.api.TestStep.run_aroundBody0(TestStep.java:79)
at cucumber.api.TestStep$AjcClosure1.run(TestStep.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at ru.sbtqa.tag.pagefactory.aspects.DataAspect.run(DataAspect.java:87)
at cucumber.api.TestStep.run(TestStep.java:78)
at cucumber.api.TestCase.run(TestCase.java:58)
at cucumber.runner.Runner.runPickle(Runner.java:80)
at cucumber.runtime.junit.PickleRunners$WithStepDescriptions.run(PickleRunners.java:95)
at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
`

**Comment by clicman** [comment]
There is somehow null path value translated in `@data` tag
