### ISSUE TITLE
Mobile android: Session ID is null. Using WebDriver after calling quit()?

### ISSUE THREAD

**Issue by SvetlanaUtina** [sbtqa/page-factory-2#275]
при запуске последовательно двух feature файлов при прогоне второго сценария сразу же падает ошибка о том, что id сессии null.
Версия mobile-plugin 14.3.1

Стектрейс:
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'svetlana-comp', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-55-generic', java.version: '1.8.0_222'
Driver info: driver.version: AppiumDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
	at io.appium.java_client.HasSessionDetails.isBrowser(HasSessionDetails.java:86)
	at io.appium.java_client.AppiumDriver.isBrowser(AppiumDriver.java:271)
	at io.appium.java_client.pagefactory.utils.WebDriverUnpackUtility.lambda$0(WebDriverUnpackUtility.java:87)
	at java.util.Optional.map(Optional.java:215)
	at io.appium.java_client.pagefactory.utils.WebDriverUnpackUtility.getCurrentContentType(WebDriverUnpackUtility.java:83)
	at io.appium.java_client.pagefactory.AppiumElementLocator.getBy(AppiumElementLocator.java:90)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:117)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.getLocation(<generated>)
	at ru.abs.stepdefs.CustomSteps.longPressElement(CustomSteps.java:100)
	at ru.abs.stepdefs.CustomSteps.synchronizationMobileWithAPI(CustomSteps.java:105)
	at ✽.synchronization mobile with REST API

**Comment by kosteman** [comment]
Добрый день!
Покажите, пожалуйста, все методы в вашем проекте, которые аннотированы как @cucumber.api.java.Before и @cucumber.api.java.After. Вероятно там есть обращение к вебдрайверу уже после того/до того как он закрыт/создан

**Comment by SvetlanaUtina** [comment]
перенесла вызов метода setUp в сам шаг.
в итоге падает, но чуть позже спустя минут 5 прогона второго фича файла.

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'svetlana-comp', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-55-generic', java.version: '1.8.0_222'
Driver info: driver.version: AndroidDriver

**Comment by kosteman** [comment]
Проблема все еще актуальна? 
Стектрейсы до и после переноса одинаковые?
В данный момент больше нет методов After и Before?

**Comment by SvetlanaUtina** [comment]
```
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'svetlana-comp', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-55-generic', java.version: '1.8.0_222'
Driver info: driver.version: AppiumDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
	at io.appium.java_client.HasSessionDetails.isBrowser(HasSessionDetails.java:86)
	at io.appium.java_client.AppiumDriver.isBrowser(AppiumDriver.java:271)
	at io.appium.java_client.pagefactory.utils.WebDriverUnpackUtility.lambda$0(WebDriverUnpackUtility.java:87)
	at java.util.Optional.map(Optional.java:215)
	at io.appium.java_client.pagefactory.utils.WebDriverUnpackUtility.getCurrentContentType(WebDriverUnpackUtility.java:83)
	at io.appium.java_client.pagefactory.AppiumElementLocator.getBy(AppiumElementLocator.java:90)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:117)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.getLocation(<generated>)
	at ru.abs.stepdefs.CustomSteps.longPressElement(CustomSteps.java:115)
	at ru.abs.stepdefs.CustomSteps.synchronizationMobileWithAPI(CustomSteps.java:120)
	at ✽.synchronization mobile with REST API
```
нет методов After и Before.
перед этим тест падает, может быть с этим связано?

**Comment by kosteman** [comment]
Пока не могу придумать, с чем может быть связана проблема. Можете скинуть полный стектрейс запуска на почту maltsevky@gmail.com?

**Comment by clicman** [comment]
Cannot reproduce
