### ISSUE TITLE
An empty Stash brokes tests and Allure reports

### ISSUE THREAD

**Issue by EkaterinaBelysheva** [sbtqa/page-factory-2#289]
Steps to reproduce:
**Case 1**
![Снимок](https://user-images.githubusercontent.com/53175863/67575115-843df300-f744-11e9-8b91-d4077d37e178.PNG)

1. Run 1st positive successful test
2.Run negative tests with steps

- Create negative step (when user clicks element which can not be found for example). 
- Add step to get smth (what wasn't saved in advance) from Stash by key ("#{key}")

_**Actual Result:**_ 

1. Test proceeds to step 2 as expected but crashes itself and crashes the allur report. 

![PNG](https://user-images.githubusercontent.com/53175863/67574695-99665200-f743-11e9-89ca-8e0bc0b62ac3.PNG)
2. Allur folder is absent
![allur-folder](https://user-images.githubusercontent.com/53175863/67574743-b26f0300-f743-11e9-820f-d82613fb5cfe.PNG)
3. junit.xml - is empty
![junitxml](https://user-images.githubusercontent.com/53175863/67574758-bc910180-f743-11e9-963a-6ad7a122d49b.PNG)
4. Info about 1 successful test is missed
5. Info (about missed element in 1st step in Negative test) is missed
6. Info about empty Stash is missed
7. All further tests are skipped
8. Allure report is damaged and doesn't show real data

_**Expected result:**_

1. Test should not crashe untill it reaches the step with Null value. It should crash exactly at the step when user calls "#{}" not earlier
2. Allur report should not be damaged
3. Info about tests shouldn't be lost
4. All tests should run

**Case 2**
![Снимок2](https://user-images.githubusercontent.com/53175863/67575193-b3ecfb00-f744-11e9-819a-1af8d7774aa7.PNG)

repeat all steps from Case1 and comment the last step 
(- Add step to get smth (what wasn't saved in advance) from Stash by key ("#{key}")) 

**_Actual result = Expected result:_**
1. Test fails but not crashed 
2. Allure report is available and includeds info about Negative test
3. All further tests were not skipped

The problem can spread vastly if any NULL Stash is used in the fragment which in its turn is used in several features. 
As it more, we allow to share the Stash between fragments - it cause a great problem. If QA creates Stash value in 1st fragment and then call it in 2d fragment and use 2d fragment separatly in any features, then we get all writen above. (becuase 1st fragment wasn't used and Stash was never initialized)

Another case when QA stores the value of any element in the Stash but element becomes unavailable. We will never know that it happend because such test crashes and is not added to report.

**Comment by kosteman** [comment]
Hello, thanks for issue.
This problem will be fixed in upcoming release 15.0.0

**Comment by maybe78** [comment]
На самом деле, если в фиче тест упал и в последующих тестах используется конструкция #{}, существует ненулевая вероятность, что возникнет NullpointerException и последующие тесты не попадут в отчет allure и json будет пустым. Дефект плавающий и очень неприятный. 

На каком этапе фича парсится на наличие диеза в параметрах?

**Comment by maybe78** [comment]
Возможно причина в функции replaceStepArguments(PickleTestStep testStep, boolean isStash) DataReplacer класса PageFactory Core?

**Comment by kosteman** [comment]
В версиях после 15.x.x тоже повторяется?
Если ли какой-нибудь стектрейс или стектрейс из дебаг-запуска?

**Comment by maybe78** [comment]
java.lang.NullPointerException
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:859)
	at java.lang.StringBuilder.replace(StringBuilder.java:262)
	at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceStashPlaceholders(DataReplacer.java:183)
	at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceData(DataReplacer.java:139)
	at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceStepArguments(DataReplacer.java:112)
	at ru.sbtqa.tag.pagefactory.data.DataReplacer.replace(DataReplacer.java:45)
	at ru.sbtqa.tag.pagefactory.data.DataReplacer.replace(DataReplacer.java:39)
	at ru.sbtqa.tag.pagefactory.aspects.DataAspect.sendStepStart(DataAspect.java:126)
	at cucumber.runner.ThreadLocalRunnerSupplier$LocalEventBus.send_aroundBody4(ThreadLocalRunnerSupplier.java:60)
	at cucumber.runner.ThreadLocalRunnerSupplier$LocalEventBus.send_aroundBody6(ThreadLocalRunnerSupplier.java:60)
	at cucumber.runner.ThreadLocalRunnerSupplier$LocalEventBus.send_aroundBody8(ThreadLocalRunnerSupplier.java:60)
	at cucumber.runner.ThreadLocalRunnerSupplier$LocalEventBus.send_aroundBody10(ThreadLocalRunnerSupplier.java:60)
	at cucumber.runner.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:60)
	at cucumber.runner.TestStep.run_aroundBody0(TestStep.java:46)
	at cucumber.runner.TestStep$AjcClosure1.run(TestStep.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at ru.sbtqa.tag.pagefactory.aspects.DataAspect.run(DataAspect.java:88)
	at cucumber.runner.TestStep.run(TestStep.java:44)
	at cucumber.runner.PickleStepTestStep.run_aroundBody0(PickleStepTestStep.java:43)
	at cucumber.runner.PickleStepTestStep$AjcClosure1.run(PickleStepTestStep.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at ru.sbtqa.tag.pagefactory.aspects.DataAspect.run(DataAspect.java:88)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:37)
	at cucumber.runner.TestCase.run(TestCase.java:46)
	at cucumber.runner.Runner.runPickle(Runner.java:49)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:123)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:65)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:147)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

**Comment by kosteman** [comment]
Тест должен упасть на шаге использущим стеш, чтобы следующий тест упал с NPE? Здесь нужно чуть больше подробностей, потому что я в своем проекте с таким не сталкивался, при том что у меня стеш очень часто используется

**Comment by maybe78** [comment]
Не обязательно на шаге со стеш, но в последующих тестах в этом же feature файле должен встречаться шаг с #{key} в параметрах.

Вот стектрейс теста, упавшего на no such element exception и выдавшего class configuration error и NPE

https://pastebin.com/gJthNiaY

Давай попробую воспроизвести в тесте на публичном сайте и скину ссылку на ветку. Норм?

**Comment by kosteman** [comment]
Да, это был бы самый идеальный вариант

**Comment by maybe78** [comment]
Не воспроизвел и понял, что мой косяк.
В моем проекте в депенденси был прописан более старый датаджек.

В новой версии все корректно и выдает нужнный ru.sbtqa.tag.datajack.exceptions.StashKeyNotFoundException.

Спасибо, ребята! Думаю можно закрывать issue.
