### ISSUE TITLE
cucumber.api.java.After not working with java.lang.ClassCastException

### ISSUE THREAD

**Issue by Sergo101010100** [sbtqa/page-factory-2#306]
Есть тест с тэгом @test

И есть для него After
```@After("@test")
public void after(){
    //
}
```
Если в фиче некорректно использовать работу со stash, то возникает ClassCastException и этот after не запускается
Сам exception
```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String

                at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceStashPlaceholders(DataReplacer.java:157)
                at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceData(DataReplacer.java:114)
                at ru.sbtqa.tag.pagefactory.data.DataReplacer.replaceStepArguments(DataReplacer.java:90)
                at ru.sbtqa.tag.pagefactory.data.DataReplacer.replace(DataReplacer.java:45)
                at ru.sbtqa.tag.pagefactory.data.DataReplacer.replace(DataReplacer.java:39)
                at ru.sbtqa.tag.pagefactory.aspects.DataAspect.sendStepStart(DataAspect.java:119)
                at cucumber.runner.EventBus.send_aroundBody4(EventBus.java:25)
                at cucumber.runner.EventBus.send_aroundBody6(EventBus.java:25)
                at cucumber.runner.EventBus.send_aroundBody8(EventBus.java:25)
                at cucumber.runner.EventBus.send_aroundBody10(EventBus.java:25)
                at cucumber.runner.EventBus.send(EventBus.java:25)
                at cucumber.api.TestStep.run_aroundBody0(TestStep.java:79)
                at cucumber.api.TestStep$AjcClosure1.run(TestStep.java:1)
                at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                at ru.sbtqa.tag.pagefactory.aspects.DataAspect.run(DataAspect.java:87)
                at cucumber.api.TestStep.run(TestStep.java:78)
                at cucumber.api.TestCase.run(TestCase.java:58)
                at cucumber.runner.Runner.runPickle(Runner.java:80)
                at cucumber.runtime.junit.PickleRunners$WithStepDescriptions.run(PickleRunners.java:95)
                at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
                at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
                at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
                at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
                at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
                at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
                at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

**Comment by clicman** [comment]
А какое поведение хотелось бы видеть?

**Comment by Sergo101010100** [comment]
Чтобы `@After` выполнялся несмотря на такие ошибки

**Comment by clicman** [comment]
Исправлено в page-factory-2-15.4.4
