### ISSUE TITLE
WebEnvironment.getBrowserName always returning same IE name

### ISSUE THREAD

**Issue by MeSaNei** [sbtqa/page-factory-2#57]
page-factory2 2.0.0
InternetExplorerDriver server (32-bit)
3.12.0.0

I'm receiving an error:
`      org.openqa.selenium.SessionNotCreatedException: No matching capability sets found.
Unable to match capability set 0: **browserName must be 'internet explorer', but was 'IE'**
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'CA-EC63000', ip: '10.76.8.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_144'
Driver info: driver.version: InternetExplorerDriver
remote stacktrace: 
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
                at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
                at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
                at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
                at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
                at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
                at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
                at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
                at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
                at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
                at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
                at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
                at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
                at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
                at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:223)
                at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:215)
                at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:160)
                at ru.sbtqa.tag.pagefactory.web.drivers.WebDriverService.createDriver(WebDriverService.java:92)
                at ru.sbtqa.tag.pagefactory.web.drivers.WebDriverService.mountDriver(WebDriverService.java:56)
                at ru.sbtqa.tag.stepdefs.CoreSetupSteps.setUp(CoreSetupSteps.java:36)
                at ru.sbtqa.tag.stepdefs.ru.CoreStepDefs.setUp(CoreStepDefs.java:21)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at cucumber.runtime.Utils$1.call(Utils.java:31)
                at cucumber.runtime.Timeout.timeout(Timeout.java:16)
                at cucumber.runtime.Utils.invoke(Utils.java:25)
                at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
                at cucumber.runtime.HookDefinitionMatch.runStep(HookDefinitionMatch.java:17)
                at cucumber.runner.UnskipableStep.executeStep(UnskipableStep.java:22)
                at cucumber.api.TestStep.run(TestStep.java:83)
                at cucumber.api.TestCase.run(TestCase.java:58)
                at cucumber.runner.Runner.runPickle(Runner.java:80)
                at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
                at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
                at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
                at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
                at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
                at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
                at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
                at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
`

In application.properties I have:
webdriver.browser.name = INTERNET_EXPLORER
And I expect to get:
`public enum BrowserName {

    IE("ie"),
    **INTERNET_EXPLORER("internet explorer"),**
    IEXPLORE("iexplore"),
    CHROME("chrome"),
    FIREFOX("firefox"),
    OPERA("firefox"),
    SAFARI("safari");

    private String name;

    BrowserName(String name) {
        this.name = name;
    }
}
`
But I recieve "ie" because of:

`public class WebEnvironment extends Environment {

    private static final WebConfiguration PROPERTIES = ConfigFactory.create(WebConfiguration.class);

    public static BrowserName getBrowserName() {
        return adaptBrowserName(PROPERTIES.getBrowserName());
    }

    private static BrowserName adaptBrowserName(String name) {
        BrowserName browserName = BrowserName.valueOf(name.toUpperCase());
        return isIE(browserName) **? BrowserName.IE** : browserName;
    }

    private static boolean isIE(BrowserName browserName) {
        return browserName.equals(BrowserName.IE)
                **|| browserName.equals(BrowserName.INTERNET_EXPLORER)**
                || browserName.equals(BrowserName.IEXPLORE);
    }
`

**Comment by clicman** [comment]
@MeSaNei получилось?

**Comment by MeSaNei** [comment]
@clicman да. Вадим Просвиряков в моей команде, он пофиксил и вам запушил.

**Comment by clicman** [comment]
Отлино! Но не забывайте отписываться, чтобы мы закрывали issues.
